config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/profile'=>'users#profile'
  resources :users do
    member do
      get :chat
      # get :profile
    end
  end
  root to: "users#index"
  resources :messages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :sent_messages, class_name: "Message", foreign_key: "sender_id"
  has_many :received_messages, class_name: "Message", foreign_key: "receiver_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = current_user.sent_messages.build(message_params)
    if @message.save
      redirect_to chat_user_path(@message.receiver_id)
    else
      flash[:error] = "Message failed to send."
      redirect_to chat_user_path(@message.receiver_id)
    end
  end

  private

  def message_params
    params.require(:message).permit(:receiver_id, :message)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:search].present?
      @users = User.where("email LIKE ?", "#{params[:search]}%").where.not(id: current_user.id).paginate(page: params[:page], per_page: 4)
    else
      @users = User.where.not(id: current_user.id).paginate(page: params[:page], per_page: 4)
    end
  end


  def chat
    @user = User.find(params[:id])
    @messages = current_user.sent_messages.where(receiver_id: @user.id).or(current_user.received_messages.where(sender_id: @user.id)).order(created_at: :asc)
    @message = Message.new

  end
  def profile

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>

  <body>
    <div>
      <nav>
        <ul style="color: #fff;font-family: 'Tilt Prism', cursive;">
          <li><h3 class="title" style="padding:5px">Chat Application</h3></li>
          <% if user_signed_in? %>
            <li style="float: right;padding: 10px"><%= button_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-light" %></li>
            <li style="float: right;padding: 3px"><%= link_to 'Show profile', profile_path %></li>
            <li style="float: right;padding: 3px"><a><%= current_user.email.split('@')[0].capitalize %></a></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>

      <div>


        <% if notice.present? %>
          <div class="alert alert-success" role="alert">
            <p id="notice"><%= notice%></p>
          </div>
        <% end %>
        <% if alert.present? %>
          <div class="alert alert-danger" role="alert">
            <p id="alert"><%= alert %></p>
          </div>
        <% end %>
      </div>
    </div>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

app/views/messages/_message.html.erb
<%= stylesheet_link_tag 'chat' %>
<% if message.sender == current_user %>
  <p  class="msg_send" style="color: #946af3" ><%= message.message %></p>
<% else %>
  <p style="color: #B00100"><%= message.message %></p>
<% end %>

app/views/users/chat.html.erb
<%= stylesheet_link_tag 'chat.css' %>
<div style="margin: 20px">
  <h4><%= @user.email.split('@')[0].capitalize %></h4>
  <%= link_to "Back to Users", users_path %>
</div>

<div class="chat card">
<!--  <h3>Chat</h3>-->


  <div class="msg">
    <!--Render form-->
    <%= render partial: "messages/message", collection: @messages %>
    <!--end-->
  </div>


  <!--Message form field-->

  <div class="msg_form">
    <%= form_with model: Message.new, url: messages_path, remote: true do |form| %>
      <%= form.hidden_field :receiver_id, value: @user.id %>
      <div class="form_input  input-group mb-3">
        <%= form.text_field :message,class: "form-control" %>
        <span class="input-group-text " id="basic-addon2"><%= form.submit "Send" %></span>
      </div>
    <% end %>
  </div>

  <!--end-->
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'user_index' %>
<div class="index">
  <h1 class="head">Users</h1>
  <div class="form">
    <%= form_for(users_path, method: :get) do %>
      <div class="form_search  input-group mb-3">
        <%= text_field_tag :search, params[:search], placeholder: "Search users",class: "form-control" %>
        <span class="input-group-text " id="basic-addon2"><%= submit_tag "Search" %></span>
      </div>
    <% end %>
  </div>


  <table class="table table-striped">
    <thead class="table-dark">
    <tr>
      <th>User Email</th>
      <th>User Name</th>
      <th>Action</th>
      <% if params[:search].present? %>
        <th>Sent messages</th>
        <th>Received messages</th>
        <th>Total messages</th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.email.split('@')[0].capitalize %></td>
        <td><%= link_to "Chat", chat_user_path(user) ,class:"btn btn-primary"%></td>
        <% if params[:search].present? %>
          <td><%= current_user.sent_messages.where(receiver_id: user.id).count %></td>
          <td><%= current_user.received_messages.where(sender_id: user.id).count %></td>
          <td><%= current_user.sent_messages.where(receiver_id: user.id).count + current_user.received_messages.where(sender_id: user.id).count %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<span class="paginate">
  <%= will_paginate @users,:page_links => false%>
</span>

app/views/users/profile.html.erb
<%= stylesheet_link_tag 'profile.css' %>
<div class="card" style="width: 500px">
  <div>
    <strong>Email:</strong>
    <%= current_user.email %>
  </div>

  <div>
    <%= link_to "Destroy account", registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete %> |
    <%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
  <!--              /* Edit Profile Button */-->
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#ProductCreateModal">
    Edit Profile
  </button>
</div>
  <!--              Edit profile form-->
  <div class="modal fade" id="ProductCreateModal" tabindex="-1" aria-labelledby="ProductCreateModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="ProductCreateModalLabel">Edit Profile</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <%= render partial: 'devise/registrations/edit', locals: {user: current_user}%>
      </div>
    </div>
  </div>
  <!--              form end-->

<%= link_to "Back to Users", users_path %>